name: Proof-It CI/CD Pipeline

on:
  push:
    branches:
      - main # Akan berjalan otomatis setiap ada push ke branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # PENTING: base-href harus sesuai dengan nama repository lu!
        run: flutter build web --base-href "/Proof-It-app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web